/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

/**
 *
 * @author Administrator
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

public class FormLapangan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLapangan.class.getName());

    /**
     * Creates new form FormLapangan
     */
    public FormLapangan() {
        initComponents();
        setLocationRelativeTo(null);
        datatable();
        kosong();
        aktif();
    }
    
    private void aktif() {
    txtNamaLapangan.requestFocus();
    txtKodeLapangan.setEditable(false);
    }
    
    private void kosong() {
    txtKodeLapangan.setText("");
    txtNamaLapangan.setText("");
    cmbJenisLantai.setSelectedIndex(0);
    txtKapasitas.setText("");
    txtHargaPerJam.setText("");
    txtDeskripsi.setText("");
    cmbStatus.setSelectedIndex(0);
    txtCari.setText("");
    autoKodeLapangan();
    }
    
    private void autoKodeLapangan() {
    try {
        Connection conn = koneksi.configDB();

        String sql = "SELECT kode_lapangan FROM lapangan "
                   + "WHERE kode_lapangan LIKE 'LAP-%' "
                   + "ORDER BY kode_lapangan DESC LIMIT 1";

        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        if (rs.next()) {
            String kodeTerakhir = rs.getString("kode_lapangan"); // contoh: LAP-G
            String hurufTerakhir = kodeTerakhir.substring(4);    // ambil G

            char huruf = hurufTerakhir.charAt(0);
            huruf++;

            txtKodeLapangan.setText("LAP-" + huruf);
        } else {
            txtKodeLapangan.setText("LAP-A");
        }

        rs.close();
        st.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal membuat kode lapangan: " + e.getMessage());
    }
    }
    
    private void datatable() {
    DefaultTableModel tbl = new DefaultTableModel();
    tbl.addColumn("ID");
    tbl.addColumn("Kode Lapangan");
    tbl.addColumn("Nama Lapangan");
    tbl.addColumn("Jenis Lantai");
    tbl.addColumn("Kapasitas");
    tbl.addColumn("Harga Per Jam");
    tbl.addColumn("Deskripsi");
    tbl.addColumn("Status");

    tblLapangan.setModel(tbl);

    try {
        Connection conn = koneksi.configDB();

        String sql = "SELECT id_lapangan, kode_lapangan, nama_lapangan, jenis_lantai, "
                   + "kapasitas, harga_per_jam, deskripsi, status "
                   + "FROM lapangan ORDER BY id_lapangan DESC";

        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            tbl.addRow(new Object[]{
                rs.getString("id_lapangan"),
                rs.getString("kode_lapangan"),
                rs.getString("nama_lapangan"),
                rs.getString("jenis_lantai"),
                rs.getString("kapasitas"),
                rs.getString("harga_per_jam"),
                rs.getString("deskripsi"),
                rs.getString("status")
            });
        }

        rs.close();
        st.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data lapangan: " + e.getMessage());
    }
    }
    
    private String ambilDataTabel(int baris, int kolom) {
    Object value = tblLapangan.getValueAt(baris, kolom);
    return value == null ? "" : value.toString();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKodeLapangan = new javax.swing.JTextField();
        txtNamaLapangan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKapasitas = new javax.swing.JTextField();
        txtHargaPerJam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDeskripsi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbJenisLantai = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLapangan = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("DATA LAPANGAN");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Kode lapangan:");

        txtKodeLapangan.addActionListener(this::txtKodeLapanganActionPerformed);

        txtNamaLapangan.addActionListener(this::txtNamaLapanganActionPerformed);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Nama Lapangan:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Kapasitas:");

        txtKapasitas.addActionListener(this::txtKapasitasActionPerformed);

        txtHargaPerJam.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtHargaPerJam.addActionListener(this::txtHargaPerJamActionPerformed);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Harga Per jam:");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Deskripsi:");

        txtDeskripsi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDeskripsi.addActionListener(this::txtDeskripsiActionPerformed);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Jenis Lantai:");

        cmbJenisLantai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vinyl", "rumput_sintetis", "parket", "semen" }));
        cmbJenisLantai.addActionListener(this::cmbJenisLantaiActionPerformed);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setText("Input Data");

        jLabel2.setText("Pencarian");

        btnCari.setText("Cari");
        btnCari.addActionListener(this::btnCariActionPerformed);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        tblLapangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLapangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLapanganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLapangan);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Status:");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tersedia", "maintenance", "tidak_aktif" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDeskripsi)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKodeLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(cmbJenisLantai, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKapasitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaLapangan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(174, 174, 174)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(193, 193, 193)
                                .addComponent(jLabel5))
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHargaPerJam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(161, 161, 161))
                            .addComponent(cmbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(53, 53, 53)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJenisLantai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHargaPerJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnClear)
                    .addComponent(btnKeluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodeLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeLapanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeLapanganActionPerformed

    private void txtNamaLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaLapanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaLapanganActionPerformed

    private void txtKapasitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKapasitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKapasitasActionPerformed

    private void txtHargaPerJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaPerJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaPerJamActionPerformed

    private void txtDeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeskripsiActionPerformed

    private void cmbJenisLantaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJenisLantaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJenisLantaiActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbl = new DefaultTableModel();
    tbl.addColumn("ID");
    tbl.addColumn("Kode Lapangan");
    tbl.addColumn("Nama Lapangan");
    tbl.addColumn("Jenis Lantai");
    tbl.addColumn("Kapasitas");
    tbl.addColumn("Harga Per Jam");
    tbl.addColumn("Deskripsi");
    tbl.addColumn("Status");

    tblLapangan.setModel(tbl);

    try {
        Connection conn = koneksi.configDB();

        String sql = "SELECT id_lapangan, kode_lapangan, nama_lapangan, jenis_lantai, "
                   + "kapasitas, harga_per_jam, deskripsi, status "
                   + "FROM lapangan "
                   + "WHERE kode_lapangan LIKE ? "
                   + "OR nama_lapangan LIKE ? "
                   + "OR jenis_lantai LIKE ? "
                   + "OR status LIKE ? "
                   + "ORDER BY id_lapangan DESC";

        PreparedStatement pst = conn.prepareStatement(sql);
        String cari = "%" + txtCari.getText().trim() + "%";

        pst.setString(1, cari);
        pst.setString(2, cari);
        pst.setString(3, cari);
        pst.setString(4, cari);

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            tbl.addRow(new Object[]{
                rs.getString("id_lapangan"),
                rs.getString("kode_lapangan"),
                rs.getString("nama_lapangan"),
                rs.getString("jenis_lantai"),
                rs.getString("kapasitas"),
                rs.getString("harga_per_jam"),
                rs.getString("deskripsi"),
                rs.getString("status")
            });
        }

        rs.close();
        pst.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mencari data lapangan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
         if (txtNamaLapangan.getText().trim().isEmpty()
            || txtKapasitas.getText().trim().isEmpty()
            || txtHargaPerJam.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this, "Nama lapangan, kapasitas, dan harga wajib diisi!");
        return;
    }

    try {
        int kapasitas = Integer.parseInt(txtKapasitas.getText().trim());
        double harga = Double.parseDouble(txtHargaPerJam.getText().trim());

        Connection conn = koneksi.configDB();

        String sql = "INSERT INTO lapangan "
                   + "(kode_lapangan, nama_lapangan, jenis_lantai, kapasitas, harga_per_jam, deskripsi, status) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txtKodeLapangan.getText());
        pst.setString(2, txtNamaLapangan.getText().trim());
        pst.setString(3, cmbJenisLantai.getSelectedItem().toString());
        pst.setInt(4, kapasitas);
        pst.setDouble(5, harga);
        pst.setString(6, txtDeskripsi.getText().trim());
        pst.setString(7, cmbStatus.getSelectedItem().toString());

        pst.executeUpdate();
        pst.close();

        JOptionPane.showMessageDialog(this, "Data lapangan berhasil disimpan.");
        datatable();
        kosong();
        aktif();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Kapasitas dan harga harus berupa angka!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data lapangan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int baris = tblLapangan.getSelectedRow();

    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data lapangan yang ingin diedit!");
        return;
    }

    if (txtNamaLapangan.getText().trim().isEmpty()
            || txtKapasitas.getText().trim().isEmpty()
            || txtHargaPerJam.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this, "Nama lapangan, kapasitas, dan harga wajib diisi!");
        return;
    }

    try {
        int kapasitas = Integer.parseInt(txtKapasitas.getText().trim());
        double harga = Double.parseDouble(txtHargaPerJam.getText().trim());

        Connection conn = koneksi.configDB();

        String sql = "UPDATE lapangan SET "
                   + "nama_lapangan = ?, "
                   + "jenis_lantai = ?, "
                   + "kapasitas = ?, "
                   + "harga_per_jam = ?, "
                   + "deskripsi = ?, "
                   + "status = ? "
                   + "WHERE kode_lapangan = ?";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txtNamaLapangan.getText().trim());
        pst.setString(2, cmbJenisLantai.getSelectedItem().toString());
        pst.setInt(3, kapasitas);
        pst.setDouble(4, harga);
        pst.setString(5, txtDeskripsi.getText().trim());
        pst.setString(6, cmbStatus.getSelectedItem().toString());
        pst.setString(7, txtKodeLapangan.getText());

        pst.executeUpdate();
        pst.close();

        JOptionPane.showMessageDialog(this, "Data lapangan berhasil diedit.");
        datatable();
        kosong();
        aktif();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Kapasitas dan harga harus berupa angka!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mengedit data lapangan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        kosong();
        aktif();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int baris = tblLapangan.getSelectedRow();

    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data lapangan yang ingin dihapus!");
        return;
    }

    int jawab = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menonaktifkan lapangan ini?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION
    );

    if (jawab != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        Connection conn = koneksi.configDB();

        String sql = "UPDATE lapangan SET status = 'tidak_aktif' WHERE kode_lapangan = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txtKodeLapangan.getText());

        pst.executeUpdate();
        pst.close();

        JOptionPane.showMessageDialog(this, "Data lapangan berhasil dinonaktifkan.");
        datatable();
        kosong();
        aktif();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menghapus data lapangan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tblLapanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLapanganMouseClicked
        // TODO add your handling code here:
        int baris = tblLapangan.rowAtPoint(evt.getPoint());

    txtKodeLapangan.setText(ambilDataTabel(baris, 1));
    txtNamaLapangan.setText(ambilDataTabel(baris, 2));
    cmbJenisLantai.setSelectedItem(ambilDataTabel(baris, 3));
    txtKapasitas.setText(ambilDataTabel(baris, 4));
    txtHargaPerJam.setText(ambilDataTabel(baris, 5));
    txtDeskripsi.setText(ambilDataTabel(baris, 6));
    cmbStatus.setSelectedItem(ambilDataTabel(baris, 7));
    }//GEN-LAST:event_tblLapanganMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLapangan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbJenisLantai;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLapangan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtHargaPerJam;
    private javax.swing.JTextField txtKapasitas;
    private javax.swing.JTextField txtKodeLapangan;
    private javax.swing.JTextField txtNamaLapangan;
    // End of variables declaration//GEN-END:variables
}
